name: Run Python script every 1 hour

on:
  schedule:
    - cron: '5 */1 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script with secrets
        env:
          FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          PERSONAL_CHAT_ID: ${{ secrets.PERSONAL_CHAT_ID }}
          GROUP_CHAT_ID: ${{ secrets.GROUP_CHAT_ID }}
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_DB: ${{ secrets.SUPABASE_DB }}
        run: python main.py
