name: Run Python script every 2 hours

on:
  schedule:
    - cron: '20 */2 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script with secrets
        env:
          API_KEY: ${{ secrets.API_KEY }}
          TOKEN: ${{ secrets.TOKEN }}
          FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
