name: Run Python script every 3 hours

on:
  schedule:
    - cron: '0 */3 * * *'  # Cada 3 horas
  workflow_dispatch:       # Permite ejecutar manualmente también

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Cambia esto a la versión que uses

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Si tienes un archivo de dependencias

      - name: Run script
        run: python /main.py  # Cambia la ruta al archivo que quieres ejecutar
